name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  publish:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.13.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install -g npm@8.19.1
      - run: npm ci
      - run: npm run build
      - run: npm test

  build-docker:
    runs-on: windows-latest
    needs: publish

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . -t frontend_docker
